# Generated by Django 4.2.5 on 2023-09-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coin", "0004_code_rotationluckreward"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rotationluckreward",
            name="code",
        ),
        migrations.RemoveField(
            model_name="rotationluckreward",
            name="user",
        ),
        migrations.AddField(
            model_name="rotationluckreward",
            name="code_with_coin_price",
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
    ]
